# Generated by Django 4.2.4 on 2023-11-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Applied', max_length=15),
        ),
    ]
