# Generated by Django 4.2.4 on 2023-11-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_applicant_resume_file_path'),
        ('jobs', '0005_alter_job_company'),
        ('job_applications', '0002_jobapplication_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('applicant', 'job')},
        ),
    ]
