# Generated by Django 4.2.4 on 2023-11-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_title_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
