# Generated by Django 4.2.4 on 2023-11-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_alter_applicant_email_alter_applicant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume_file_path',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
