# Generated by Django 4.2.4 on 2023-11-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_applicant_resume_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='resume_file_path',
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(default='<django.db.models.fields.EmailField>.resume', upload_to='applicant_resumes/'),
        ),
    ]
