# Generated by Django 4.2.4 on 2023-11-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_remove_applicant_resume_file_path_applicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(upload_to='applicant_resumes/'),
        ),
    ]
