# Generated by Django 4.2.4 on 2023-11-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_alter_applicant_resume_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='resume_file_path',
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='applicant_resumes/'),
        ),
    ]
